default: &default
  adapter: "mysql2"
  host: "localhost"
  database: "locatest"
  username: "root"
  password:

development:
  <<: *default
  database: locatest_development

test:
  <<: *default
  database: locatest_test

production:
  <<: *default
  database: locatest_production
  username: locatest
  password: <%= ENV['LOCATEST_DATABASE_PASSWORD'] %>
